
version: "3.4"

services:
  php:
    build:
      context: .
      target: symfony_php
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - app-network
  nginx:
    image: nginx:alpine
    container_name: nginx
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
      - ./:/var/www
    links:
      - php
    networks:
      - app-network


networks:
  app-network:
    driver: bridge
