
version: "3.4"

services:
  php:
    build:
      context: .
      target: symfony_php
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - app-network
  nginx:
    image: nginx:alpine
    container_name: nginx
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
      - ./:/var/www
    links:
      - php
    networks:
      - app-network


  database:
    image: mariadb:10.6
    restart: on-failure
    volumes:
      - ./docker/volumes/mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: winestyle_local
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - 3306:3306
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
