App\Domain\Entity\Review:
  collectionOperations:
    addReview:
      method: 'POST'
      input: App\App\Command\AddNewReviewCommand
      output: false
#      route_name: 'review_add'
      controller: App\Controller\AddReviewController
  itemOperations: []

